---
name: test
on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.24'
          - latest
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v1

      - name: perl-version
        run: perl -V

      - uses: actions/cache@v1
        id: cache
        with:
          path: /usr/local/lib/perl5
          key: ${{ runner.os }}-perl-${{ matrix.perl-version }}-${{ hashFiles('cpanfile', '.github/workflows/test.yml') }}

      - name: install deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cpanm --notest --installdeps .
      - name: test
        run: prove -Ilib