---
name: update-cpanfile
on:
  schedule:
  - cron:  '0 0 * * *'

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: update
        run: docker run --rm -v `pwd`:/src -w /src perl:latest bash -c 'perl -v && cpanm --notest App::UpdateCPANfile && update-cpanfile update'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          title: 'Update cpanfile'
          branch: update-cpanfile

