---
name: update-cpanfile
on:
  pull_request:
  schedule:
  - cron:  '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: perl:latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: perl-version
        run: perl -V

      - name: install deps
        run: |
          cpanm --notest --installdeps .
      - name: update
        run: perl -Ilib/ script/update-cpanfile update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update cpanfile
          branch: update-cpanfile
          base: master
